# Prueba del microservicio
GET  http://127.0.0.1:8000

### Obtener todos los usuarios
GET http://localhost:8000/usuarios/all

### Login usuario
POST http://127.0.0.1:8000/usuarios/login
Content-Type: application/json

{
  "email": "admin@system.com",
  "password": "admin123"
}

### Registrar usuario (Solo Administrador)
POST http://127.0.0.1:8000/usuarios/register
Authorization: Bearer e5e53bbb6966d79f95418fa1f7d5667a7f4815d79e733974df8a9db611fd848f
Content-Type: application/json

{
    "name": "Nuevo Gestor2",
    "email": "nuevo@gestor2.com",
    "password": "gestor123",
    "role": "gestor"
}

### Obtener vuelos
GET http://127.0.0.1:8001/vuelos/all


### Crear vuelo (Solo Administrador)
PUT http://127.0.0.1:8001/vuelos/update/3
Content-Type: application/json
Authorization: Bearer test

{
  "origin": "Bogotá",
  "destination": "Cali",
  "price": 999999
}

### Eliminar vuelo (Solo Administrador)
DELETE http://127.0.0.1:8001/vuelos/delete/ID



### Eliminar vuelo
DELETE http://127.0.0.1:8001/vuelos/delete/1
Content-Type: application/json

GET http://127.0.0.1:8001/reservas/mias
Authorization: Bearer <token del gestor>


POST http://127.0.0.1:8001/reservas/create
Content-Type: application/json
Authorization: Bearer <token>

{
  "flight_id": 2
}

POST http://127.0.0.1:8001/naves/create

GET http://127.0.0.1:8001/naves/all

PUT http://127.0.0.1:8001/naves/update/{id}

DELETE http://127.0.0.1:8001/naves/delete/{id}

